#FROM bingliunpu/pytorch1.8.1-py38-cuda11.1-cudnn8-ubuntu18.04:latest
From zombbie/cuda11.1-cudnn8-ubuntu20.04:v1.0
LABEL description="pytorch 1.8.1 cuda 11.1" version="1.0" owner="yjyeh" maintainer="yjyeh"
#ENV workspace /var/www/localhost/htdocs/
ENV ENV_PATH $HOME/.visdom
ENV LOGGING_LEVEL=INFO
ENV HOSTNAME=localhost
ENV BASE_URL=/
ENV READONLY=True
ENV ENABLE_LOGIN=False
ENV FORCE_NEW_COOKIE=False
ENV NO_PROXY="localhost,127.0.0.1"
ENV PATH="/usr/bin:$PATH"
ENV PYTHONPATH="/usr/local/lib/python3.9/dist-packages"
RUN echo $PATH

RUN pwd
WORKDIR /708HDD2/yjyeh/project/how-to-autorl/
COPY . /708HDD2/yjyeh/project/how-to-autorl/

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub &&\
    apt-get update &&\
    apt-get install software-properties-common -y &&\
    add-apt-repository ppa:deadsnakes/ppa &&\
    # Install py39 from deadsnakes repository
    apt-get install python3.9 -y &&\
    # Install pip from standard ubuntu packages
    apt-get install python3-pip -y &&\
    apt-get install python3.9-dev build-essential -y &&\
    python3.9 -V &&\
    find / -iname 'Python.h' &&\
    #rm /opt/miniconda/bin/python && rm /opt/miniconda/bin/python3 && rm /opt/miniconda/bin/python3-config &&\
    #ln -s /opt/miniconda/bin/python3.9 /opt/miniconda/bin/python &&  ln -s /opt/miniconda/bin/python3.9 /opt/miniconda/bin/python3 &&\
    #ln -s /opt/miniconda/bin/python3.9-config /opt/miniconda/bin/python3-config &&\
#    update-alternatives --install /usr/bin/python python3 /usr/bin/python3.8 1 && \
#    update-alternatives --install /usr/bin/python python3 /usr/bin/python3.9 2 && \
#    update-alternatives --set python /usr/bin/python3.9 && \
    #update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1 && \
    #update-alternatives --set python3 /usr/bin/python3.9 && \
    ls -al /usr/bin/python* &&\
    ls -al /etc/alternatives/python3* &&\
    which python3 &&\
    python3 -V &&\
    python3 -m pip install Pillow --upgrade &&\
#RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub &&\
#    apk update && apk install -y software-properties-common &&\
#    add-apt-repository ppa:deadsnakes/ppa -y && apk update  &&\ apt-get install -y python3.9 &&\
#RUN ln -s /usr/bin/pip3 /usr/bin/pip && \
#    ln -s /usr/bin/python3.8 /usr/bin/python
#RUN apt-get install -y python3-pip python-dev python3.9-dev && python3 -m pip install pip --upgrade
#RUN rm /usr/bin/python && rm /usr/bin/python3  && ln -s /usr/bin/python3.9 /usr/bin/python &&  ln -s /usr/bin/python3.9 /usr/bin/python3 \
#    && rm /usr/local/bin/python && rm /usr/local/bin/python3 && ln -s /usr/bin/python3.9 /usr/local/bin/python &&  ln -s /usr/bin/python3.9 /usr/local/bin/python3 \
#    && apt-get install -y python3-pip python-dev python3.9-dev && python3 -m pip install pip --upgrade
    pip install werkzeug==2.0.3 &&\
    pip install flask==2.0.3 &&\
    pip install swig &&\
#    git clone git@github.com:automl/DeepCAVE.git &&\
#    pip install -e DeepCAVE &&\

    cd deepcave-1.1.1 &&\
    pwd &&\
    pip install . &&\
    pip install matplotlib==3.5.1 &&\
    cd .. &&\
    pip install dehb &&\
    pip install -e . &&\
    pip install gymnasium &&\
    pip install stable-baselines3[extra] &&\
    pip install gpy &&\
    pip install gpytorch &&\
    pip list
    #cp ./init_config_space.py /usr/local/lib/python3.9/dist-packages/ConfigSpace/hyperparameters/__init__.py

  #,pb2,bgt]


#RUN python -m visdom.server
EXPOSE 8050
#EXPOSE 8097
#ENTRYPOINT ["httpd", "-D", "FOREGROUND"]


#--entrypoint -v /708HDD2/yjyeh/project/gnn_drl_fjsp:/opt/project -v /708HDD2/yjyeh/static:/root/.visdom -p 8097:8097 --rm --gpus all