#FROM bingliunpu/pytorch1.8.1-py38-cuda11.1-cudnn8-ubuntu18.04:latest
From zombbie/cuda11.1-cudnn8-ubuntu20.04:v1.0
LABEL description="pytorch 1.8.1 cuda 11.1" version="1.0" owner="yjyeh" maintainer="yjyeh"
#ENV workspace /var/www/localhost/htdocs/
ENV ENV_PATH $HOME/.visdom
ENV LOGGING_LEVEL=INFO
ENV HOSTNAME=localhost
ENV BASE_URL=/
ENV READONLY=True
ENV ENABLE_LOGIN=False
ENV FORCE_NEW_COOKIE=False
ENV NO_PROXY="localhost,127.0.0.1"
ENV PATH="/usr/bin:$PATH"
ENV PYTHONPATH="/708HDD2/yjyeh/project/how-to-autorl_fjsp:/708HDD2/yjyeh/project/how-to-autorl_fjsp/gnn_drl_fjsp:./gnn_drl_fjsp:/usr/local/lib/python3.9/dist-packages"
RUN echo $PATH

RUN pwd
WORKDIR /708HDD2/yjyeh/project/how-to-autorl_fjsp/
COPY . /708HDD2/yjyeh/project/how-to-autorl_fjsp/

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub &&\
    apt-get update &&\
    apt-get install software-properties-common -y &&\
    add-apt-repository ppa:deadsnakes/ppa &&\
    # Install py39 from deadsnakes repository
    apt-get install python3.9 -y &&\
    # Install pip from standard ubuntu packages
    apt-get install python3-pip -y &&\
    apt-get install python3.9-dev build-essential -y &&\
    python3.9 -V &&\
    find / -iname 'Python.h' &&\
    #rm /opt/miniconda/bin/python && rm /opt/miniconda/bin/python3 && rm /opt/miniconda/bin/python3-config &&\
    #ln -s /opt/miniconda/bin/python3.9 /opt/miniconda/bin/python &&  ln -s /opt/miniconda/bin/python3.9 /opt/miniconda/bin/python3 &&\
    #ln -s /opt/miniconda/bin/python3.9-config /opt/miniconda/bin/python3-config &&\
#    update-alternatives --install /usr/bin/python python3 /usr/bin/python3.8 1 && \
#    update-alternatives --install /usr/bin/python python3 /usr/bin/python3.9 2 && \
#    update-alternatives --set python /usr/bin/python3.9 && \
    #update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1 && \
    #update-alternatives --set python3 /usr/bin/python3.9 && \
    rm /usr/bin/python3-config &&\
    ln -s /usr/bin/python3.8-config  /usr/bin/python3-config &&\
    ls -al /usr/bin/python* &&\
    ls -al /etc/alternatives/python3* &&\
    which python3 &&\
    python3 -V &&\
    pip install torch==1.13.1+cu116 torchvision==0.13.0+cu116 -f https://download.pytorch.org/whl/torch_stable.html --default-timeout=1000 &&\
    pip install -r /708HDD2/yjyeh/project/how-to-autorl_fjsp/requirements.txt &&\
    pwd &&\
    cd deepcave-1.1.1 &&\
    pwd &&\
    pip install . &&\
    cd .. &&\
    pip install -e . &&\
    #pip install torch==1.10.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html --default-timeout=1000 &&\
    #pip install torch==1.12.0+cu113 torchvision==0.11.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html --default-timeout=1000 &&\
    pip install -U pillow


  #,pb2,bgt]


#RUN python -m visdom.server
EXPOSE 8050
#EXPOSE 8097
#ENTRYPOINT ["httpd", "-D", "FOREGROUND"]


#--entrypoint -v /708HDD2/yjyeh/project/gnn_drl_fjsp:/opt/project -v /708HDD2/yjyeh/static:/root/.visdom -p 8097:8097 --rm --gpus all